CREATE DATABASE ShopDB;
USE ShopDB;

CREATE TABLE Products1 (
    ID INT AUTO_INCREMENT,
    Name VARCHAR(50),
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

INSERT INTO Products1 (Name) VALUES
    ('AwersomeProduct1'),
    ('AwersomeProduct2'),
    ('AwersomeProduct3'),
    ('AwersomeProduct4'),
    ('AwersomeProduct5'),
    ('AwersomeProduct6'),
    ('AwersomeProduct7'),
    ('AwersomeProduct8'),
    ('AwersomeProduct9'),
    ('AwersomeProduct10'),
    ('AwersomeProduct11'),
    ('AwersomeProduct12'),
    ('AwersomeProduct13'),
    ('AwersomeProduct14'),
    ('AwersomeProduct15'),
    ('AwersomeProduct16'),
    ('AwersomeProduct17'),
    ('AwersomeProduct18'),
    ('AwersomeProduct19'),
    ('AwersomeProduct20'),
    ('AwersomeProduct21'),
    ('AwersomeProduct22'),
    ('AwersomeProduct23'),
    ('AwersomeProduct24'),
    ('AwersomeProduct25'),
    ('AwersomeProduct26'),
    ('AwersomeProduct27'),
    ('AwersomeProduct28'),
    ('AwersomeProduct29'),
    ('AwersomeProduct30'),
    ('AwersomeProduct31'),
    ('AwersomeProduct32'),
    ('AwersomeProduct33'),
    ('AwersomeProduct34'),
    ('AwersomeProduct35'),
    ('AwersomeProduct36'),
    ('AwersomeProduct37'),
    ('AwersomeProduct38'),
    ('AwersomeProduct39'),
    ('AwersomeProduct40'),
    ('AwersomeProduct41'),
    ('AwersomeProduct42'),
    ('AwersomeProduct43'),
    ('AwersomeProduct44'),
    ('AwersomeProduct45'),
    ('AwersomeProduct46'),
    ('AwersomeProduct47'),
    ('AwersomeProduct48'),
    ('AwersomeProduct49'),
    ('AwersomeProduct50'),
    ('AwersomeProduct51'),
    ('AwersomeProduct52'),
    ('AwersomeProduct53'),
    ('AwersomeProduct54'),
    ('AwersomeProduct55'),
    ('AwersomeProduct56'),
    ('AwersomeProduct57'),
    ('AwersomeProduct58'),
    ('AwersomeProduct59'),
    ('AwersomeProduct60');
